[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "EDM2u17mFtGncf48rGCDNpB3qtfefZF7ZCnMg3Aok5K2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/mnt/c/Users/Fadex/Desktop/staking/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
